# HOS development environment
# Copyright (C) 1998-2022 by Project HOS
# http://sourceforge.jp/projects/hos/

FROM __CONTAINER_IMAGE__

# [Optional] Uncomment this section to install additional vcpkg ports.
# RUN su vscode -c "${VCPKG_ROOT}/vcpkg install <your-port-name-here>"

# [Optional] Uncomment this section to install additional packages.
#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends <additional-packages>
